global:
  domain: cffc19e.stage.kyma.ondemand.com
  imagePullSecret:
    name: container-registry
srv:
  bindings:
    destination:
      serviceInstanceName: 'destination'
    auth:
      serviceInstanceName: xsuaa
    db:
      serviceInstanceName: hana
  image:
    repository: farozanfarman/incident-management-srv
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
  expose:
    enabled: false
  networkSecurity:
    allowNamespaceInternal: true
destination:
  serviceOfferingName: 'destination'
  servicePlanName: 'lite'
  parameters:
    version: '1.0.0'
    HTML5Runtime_enabled: true
html5-apps-repo-host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
html5-apps-deployer:
  image:
    repository: "farozanfarman/incident-management-html5-deployer"
    tag: latest
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    html5-apps-repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-html5-apps-deployer-configmap"
backendDestinations:
  srv-api:
    service: srv
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: incident-management
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
        - https://*.cffc19e.stage.kyma.ondemand.com/**
approuter:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    html5-apps-repo-runtime:
      serviceInstanceName: html5-apps-repo-runtime
    portal:
      serviceInstanceName: portal
      parameters:
        appguid: ""
        app_guid: ""
        content-endpoint: developer
  image:
    repository: farozanfarman/incident-management-approuter
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-approuter-configmap"
portal-deployer:
  image:
    repository: farozanfarman/incident-management-portalcontent
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  bindings:
    auth:
      serviceInstanceName: xsuaa
    html5-apps-repo-host:
      serviceInstanceName: html5-apps-repo-host
    portal:
      serviceInstanceName: portal
  env:
    SERVICE_BINDING_ROOT: /bindings
    BPL_VCAP_SERVICES_ENABLED: "true"
    XSUAA_CREDENTIALS:
      secretKeyRef:
        name: "{{ .Release.Name }}-approuter-auth"
        key: credentials
    REPOHOST_CREDENTIALS:
      secretKeyRef:
        name: "{{ .Release.Name }}-html5-apps-deployer-html5-apps-repo"
        key: credentials
    PORTAL_CREDENTIALS:
      secretKeyRef:
        name: "{{ .Release.Name }}-approuter-portal"
        key: credentials
hana-deployer:
  image:
    repository: farozanfarman/incident-management-hana-deployer
    tag: latest
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
html5-apps-repo-runtime:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-runtime
portal:
  serviceOfferingName: portal
  servicePlanName: standard
s4-hana-cloud:
  serviceOfferingName: s4-hana-cloud
  servicePlanName: api-access
